// Types generated by ChatGPT
declare module "instant-yaml" {
  export namespace YAML {
    interface Token {
      depth: number
      line: number
      column: number
      isProperty?: boolean
      isArrayItem?: boolean
      propertyName?: string
      value?: any
      folded?: string
      quotedValue?: number
      foldedIndentation?: number
    }

    /**
     * Parses a YAML string and returns the resulting JavaScript object.
     *
     * @param code - YAML code as a string or already-parsed object.
     * @param tokens - Optional array to collect detailed parsing tokens.
     * @returns Parsed object.
     */
    function parse(code: string | object, tokens?: Token[]): object

    /**
     * Consumes a parsed node and applies it to the current context stack.
     *
     * @param node - The parsed token node to consume.
     * @param contextStack - Internal parsing stack for nesting.
     * @param tokensCollector - Array to collect the tokens.
     */
    function consume(
      node: Token,
      contextStack: {
        depth: number
        selector: string | number | null
        ref: any
      }[],
      tokensCollector: Token[]
    ): void
  }
}
