// Type definitions generated by ChatGPT
// See https://ysws.hackclub.com/data.yml
type YSWSStatus = "active" | "ended" | "draft"

interface YSWSCatalogItem {
  name: string
  description: string
  detailedDescription?: string
  website?: string
  slack?: string
  slackChannel?: string
  status?: YSWSStatus
  deadline?: string // ISO date string
  ended?: string // ISO date string (for ended events only)
  participants?: number
  requirements?: string[]
  steps?: string[]
  details?: string[]
}

interface YSWSCatalog {
  limitedTime: YSWSCatalogItem[]
  indefinite: YSWSCatalogItem[]
  drafts: YSWSCatalogItem[]
}
